//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSMaterialPreparation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SMPPDI01.pasmydc.local:8000/sap/bc/srt/rfc/sap/zwm_my_i_prod_sched/010/zwm" +
            "_my_i_prod_sched/prod_sched")]
        public string EMSMaterialPreparation_GETProductionInfo_ZWM_MY_I_PROD_SCHED {
            get {
                return ((string)(this["EMSMaterialPreparation_GETProductionInfo_ZWM_MY_I_PROD_SCHED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SMPPDI01.pasmydc.local:8000/sap/bc/srt/rfc/sap/zim_get_ems_stock/010/zim_g" +
            "et_ems_stock/ems_stock")]
        public string EMSMaterialPreparation_GET_STOCK_PASMY_EMS_ZIM_GET_EMS_STOCK {
            get {
                return ((string)(this["EMSMaterialPreparation_GET_STOCK_PASMY_EMS_ZIM_GET_EMS_STOCK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SMPPDI01.pasmydc.local:8000/sap/bc/srt/rfc/sap/zim_get_vendor_stock/010/zi" +
            "m_get_vendor_stock/vendor_stock")]
        public string EMSMaterialPreparation_GETEMSVENDORSTOCK_ZIM_GET_VENDOR_STOCK {
            get {
                return ((string)(this["EMSMaterialPreparation_GETEMSVENDORSTOCK_ZIM_GET_VENDOR_STOCK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SMPPDI01.pasmydc.local:8000/sap/bc/srt/rfc/sap/zwm_my_i_barc_stock/010/zwm" +
            "_my_i_barc_stock/barc_stock")]
        public string EMSMaterialPreparation_BARC_STOCK_ZWM_MY_I_BARC_STOCK {
            get {
                return ((string)(this["EMSMaterialPreparation_BARC_STOCK_ZWM_MY_I_BARC_STOCK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://SMPPDI01.pasmydc.local:8000/sap/bc/srt/rfc/sap/zwm_i_mfrpn_barc/010/zwm_i_" +
            "mfrpn_barc/mfrpn_barc")]
        public string EMSMaterialPreparation_GET_LOCATION_ZWM_I_MFRPN_BARC {
            get {
                return ((string)(this["EMSMaterialPreparation_GET_LOCATION_ZWM_I_MFRPN_BARC"]));
            }
        }
    }
}
